#!/usr/bin/env bash
# =============================================================================
# scripts/publish-tap.sh — Homebrew tap 자동 게시 / Auto-publish Homebrew tap
# -----------------------------------------------------------------------------
# 사용법 / Usage:
#   ./scripts/publish-tap.sh                 # GoGoComputer/homebrew-openclaw 에 게시
#   GH_OWNER=myorg ./scripts/publish-tap.sh  # 다른 owner 로 게시 (fork 용)
#
# 무엇을 하나 / What it does:
#   1) 메인 저장소 v0.1.0 태그의 tarball SHA256 계산
#   2) 로컬에 homebrew-openclaw 스켈레톤 생성 (Formula/ + README)
#   3) gh CLI 로 <owner>/homebrew-openclaw 저장소 생성·푸시 (이미 있으면 push 만)
#   4) 사용자에게 `brew tap` / `brew install` 명령 출력
#
# 전제조건 / Prerequisites:
#   - gh CLI 설치 + 로그인 (`gh auth login`)
#   - 메인 저장소 v0.1.0 태그가 GitHub 에 푸시되어 있어야 함
#
# Copyright 2026 박성모 Park Sungmo — MIT License
# =============================================================================
set -euo pipefail

# ── 색상 ───────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  C_RED=$'\033[0;31m'; C_GRN=$'\033[0;32m'; C_YEL=$'\033[1;33m'
  C_BLU=$'\033[0;34m'; C_RST=$'\033[0m'
else
  C_RED=""; C_GRN=""; C_YEL=""; C_BLU=""; C_RST=""
fi
info() { printf '%s▶%s %s\n' "$C_BLU" "$C_RST" "$*"; }
ok()   { printf '%s✔%s %s\n' "$C_GRN" "$C_RST" "$*"; }
warn() { printf '%s⚠%s %s\n' "$C_YEL" "$C_RST" "$*" >&2; }
die()  { printf '%s✗%s %s\n' "$C_RED" "$C_RST" "$*" >&2; exit 1; }

# ── 설정 ───────────────────────────────────────────────────────────────────────
GH_OWNER="${GH_OWNER:-GoGoComputer}"          # tap 저장소 owner
GH_REPO="homebrew-openclaw"                   # 반드시 'homebrew-' 접두사 (Homebrew 규칙)
SRC_OWNER="GoGoComputer"                      # 메인 코드 저장소 owner
SRC_REPO="openclaw-workspace"
TAG="${TAG:-v0.1.0}"
FORMULA_NAME="openclaw-workspace"
WORK_DIR="${TMPDIR:-/tmp}/openclaw-tap-publish.$$"

cleanup() { rm -rf -- "$WORK_DIR"; }
trap cleanup EXIT

# ── 사전 점검 ─────────────────────────────────────────────────────────────────
command -v gh    >/dev/null 2>&1 || die "gh CLI 가 필요합니다 (brew install gh)"
command -v git   >/dev/null 2>&1 || die "git 가 필요합니다"
command -v curl  >/dev/null 2>&1 || die "curl 가 필요합니다"
command -v shasum >/dev/null 2>&1 || die "shasum 이 필요합니다 (macOS 기본)"
gh auth status >/dev/null 2>&1   || die "gh 인증 필요: 'gh auth login' 먼저 실행"

info "Tap owner = ${GH_OWNER}, source = ${SRC_OWNER}/${SRC_REPO}@${TAG}"

# ── 1) 메인 tarball SHA256 ────────────────────────────────────────────────────
TARBALL_URL="https://github.com/${SRC_OWNER}/${SRC_REPO}/archive/refs/tags/${TAG}.tar.gz"
info "Tarball SHA256 계산 중..."
SHA256="$(curl -fsSL "$TARBALL_URL" | shasum -a 256 | awk '{print $1}')"
[ -n "$SHA256" ] && [ "${#SHA256}" -eq 64 ] || die "SHA256 계산 실패"
ok "SHA256: $SHA256"

# ── 2) 로컬 tap 스켈레톤 ──────────────────────────────────────────────────────
mkdir -p "$WORK_DIR/Formula"
cd "$WORK_DIR"

VERSION="${TAG#v}"
GH_OWNER_LC="$(printf '%s' "$GH_OWNER" | tr '[:upper:]' '[:lower:]')"

cat > "Formula/${FORMULA_NAME}.rb" <<RUBY
# typed: false
# frozen_string_literal: true

# Auto-generated by scripts/publish-tap.sh — DO NOT EDIT BY HAND.
# 이 파일은 메인 저장소의 publish-tap.sh 가 자동 생성합니다. 수동 편집 금지.
class OpenclawWorkspace < Formula
  desc "macOS self-host automation for OpenClaw (one-line install/maintain/uninstall)"
  homepage "https://github.com/${SRC_OWNER}/${SRC_REPO}"
  url "${TARBALL_URL}"
  sha256 "${SHA256}"
  license "MIT"
  version "${VERSION}"

  depends_on :macos
  depends_on "bash" => :recommended

  def install
    libexec.install Dir["openclaw-mgr/*"]
    libexec.install Dir["openclaw-mgr/.env.example"] if File.exist?("openclaw-mgr/.env.example")

    (bin/"openclaw").write <<~SH
      #!/bin/bash
      exec "#{libexec}/openclaw" "\$@"
    SH
    chmod 0755, bin/"openclaw"

    doc.install "README.md", "README.en.md", "LICENSE", "SECURITY.md"
    (doc/"docs").install Dir["docs/*"]
  end

  def caveats
    <<~EOS
      🦞 openclaw-workspace installed!

      Run the interactive menu (auto-detects Korean/English):
        openclaw

      Or invoke subcommands directly:
        openclaw doctor          # diagnose
        openclaw install         # auto-install Docker / Ollama / OpenClaw

      First run auto-creates ~/.openclaw-mgr/.env from the template.
      State is kept in ~/.openclaw-mgr/   (survives brew upgrades).

      Docker Desktop and Ollama are auto-installed by 'openclaw install'
      if missing — no need to brew them yourself.

      Docs: #{HOMEBREW_PREFIX}/share/doc/openclaw-workspace/
      Repo: https://github.com/${SRC_OWNER}/${SRC_REPO}
    EOS
  end

  test do
    assert_match "openclaw-mgr", shell_output("#{bin}/openclaw --version")
    help = shell_output("#{bin}/openclaw help")
    %w[doctor install start stop logs update backup restore schedule network clean uninstall].each do |sub|
      assert_match sub, help
    end
  end
end
RUBY
ok "Formula 생성: Formula/${FORMULA_NAME}.rb"

cat > "README.md" <<MD
# homebrew-openclaw

Homebrew tap for [openclaw-workspace](https://github.com/${SRC_OWNER}/${SRC_REPO}).

## 사용법 / Usage

\`\`\`bash
brew tap ${GH_OWNER_LC}/openclaw   # tap 등록 (한 번만)
brew install openclaw-workspace   # 설치
openclaw                          # 실행 (대화형 메뉴, KO/EN 자동)
\`\`\`

> macOS 만 지원. Docker Desktop / Ollama 는 \`openclaw install\` 이 자동 설치합니다.

## 업데이트 / Update

\`\`\`bash
brew update && brew upgrade openclaw-workspace
\`\`\`

## 제거 / Uninstall

\`\`\`bash
openclaw uninstall          # OpenClaw 컨테이너 제거 (Docker 는 보존)
brew uninstall openclaw-workspace
brew untap ${GH_OWNER_LC}/openclaw
\`\`\`

자세한 문서는 [메인 저장소 README](https://github.com/${SRC_OWNER}/${SRC_REPO}) 를 보세요.

## License

MIT — see [main repo](https://github.com/${SRC_OWNER}/${SRC_REPO}/blob/main/LICENSE).
MD

git init -q -b main
git add -A
git -c user.email="publish-tap@local" -c user.name="publish-tap" \
    commit -q -m "feat: ${FORMULA_NAME} ${VERSION}"
ok "로컬 tap 저장소 초기화 완료"

# ── 3) GitHub 저장소 생성 또는 push ──────────────────────────────────────────
if gh repo view "${GH_OWNER}/${GH_REPO}" >/dev/null 2>&1; then
  warn "${GH_OWNER}/${GH_REPO} 이미 존재 — 강제 push 합니다"
  git remote add origin "https://github.com/${GH_OWNER}/${GH_REPO}.git"
  git push -f origin main
else
  info "${GH_OWNER}/${GH_REPO} 생성 중..."
  gh repo create "${GH_OWNER}/${GH_REPO}" \
    --public \
    --source=. --remote=origin --push \
    --description "Homebrew tap for openclaw-workspace (macOS self-host automation)" \
    --homepage "https://github.com/${SRC_OWNER}/${SRC_REPO}"
fi
ok "tap 저장소 게시 완료: https://github.com/${GH_OWNER}/${GH_REPO}"

# ── 4) 사용자 안내 ────────────────────────────────────────────────────────────
cat <<EOF

${C_GRN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RST}
${C_GRN}✔ Homebrew tap 게시 성공!${C_RST}
${C_GRN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RST}

이제 누구나 다음 한 줄로 설치할 수 있습니다 / Anyone can now install with:

  ${C_BLU}brew tap ${GH_OWNER_LC}/openclaw${C_RST}
  ${C_BLU}brew install openclaw-workspace${C_RST}
  ${C_BLU}openclaw${C_RST}

또는 한 줄로 / Or in one line:

  ${C_BLU}brew install ${GH_OWNER_LC}/openclaw/openclaw-workspace${C_RST}

tap 저장소: https://github.com/${GH_OWNER}/${GH_REPO}

다음 릴리스(v0.1.1 등) 발행 후에는 이 스크립트를 다시 실행하세요:
After publishing the next release, re-run this script:

  ${C_BLU}TAG=v0.1.1 ./scripts/publish-tap.sh${C_RST}

EOF
